# Generated by Django 4.1.1 on 2022-09-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="read_more_url",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="website_url",
            field=models.URLField(default="https://j.com"),
            preserve_default=False,
        ),
    ]
